define_directive {v:work.MobileNet} {.noprune} {1}
define_directive {v:work.MobileNet} {.distcompnoprune} {1}
define_directive {v:work.fc} {.noprune} {1}
define_directive {v:work.fc} {.distcompnoprune} {1}
define_directive {v:work.conv} {.noprune} {1}
define_directive {v:work.conv} {.distcompnoprune} {1}
define_directive {v:work.window} {.noprune} {1}
define_directive {v:work.window} {.distcompnoprune} {1}
define_directive {v:work.MobileNet} {.distcompmodetop} {1}
